FROM jenkins/jenkins:lts

USER root

# ติดตั้ง dependencies
RUN apt-get update && apt-get install -y \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    git \
    procps \
    && rm -rf /var/lib/apt/lists/*
    
# GIT
RUN git config --system --add safe.directory '*'

# Docker CLI + Compose
RUN mkdir -p /etc/apt/keyrings \
    && curl -fsSL https://download.docker.com/linux/debian/gpg | tee /etc/apt/keyrings/docker.asc > /dev/null \
    && chmod a+r /etc/apt/keyrings/docker.asc \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(lsb_release -cs) stable" \
       | tee /etc/apt/sources.list.d/docker.list > /dev/null

RUN apt-get update && apt-get install -y docker-ce-cli docker-compose-plugin && rm -rf /var/lib/apt/lists/*

# git safe directory (แก้ error fatal: not in a git directory)
RUN git config --system --add safe.directory '*'

USER jenkins
