version: '3.9'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    image: jenkins-docker:lts
    container_name: jenkins
    user: root
    environment:
      DOCKER_HOST: tcp://host.docker.internal:2375
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped

  nestapp:
    build: .
    container_name: nestapp
    command: ['pnpm', 'start:prod']
    ports:
      - "3005:3005"
    restart: unless-stopped

volumes:
  jenkins_home:
