version: '3.9'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    image: jenkins-docker:lts
    container_name: jenkins
    user: root
    environment:
      DOCKER_HOST: tcp://dind:2375   # ✅ ให้ jenkins ใช้ docker daemon ของ dind
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped
    depends_on:
      - dind

  dind:
    image: docker:24.0-dind    # ✅ Docker daemon
    privileged: true           # ✅ ต้อง privileged
    container_name: dind
    ports:
      - "2375:2375"
    environment:
      DOCKER_TLS_CERTDIR: ""   # ✅ ปิด TLS เพื่อให้ connect ได้ง่าย
    volumes:
      - dind-storage:/var/lib/docker

  nestapp:
    build: .
    container_name: nestapp
    command: ['pnpm', 'start:prod']
    ports:
      - "3005:3005"
    restart: unless-stopped

volumes:
  jenkins_home:
  dind-storage:
