version: '3.9'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  nestapp:
    build: .              # 🔑 root directory
    container_name: nestapp
    command: ["pnpm", "start:prod"]
    volumes:
      - .:/usr/src/app    # mount project root เข้า container
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  jenkins_home:
